---
- hosts: any
  become: true
  tasks:

# tasks file for webapp

    - name: update
      command: sudo apt update
      become: true


    - name: install nodejs
      apt:
        pkg: nodejs
        state: present
      become: true

    - name: install git
      apt:
        pkg: git
        state: present
      become: true

    - name: Creates directory
      file:
        path: /home/ansible/hms
        state: directory
      become: true

    - name: Clone a github repository
      git:
        repo: https://github.com/ManjunathNayak-23/Nodejsdemo.git
        dest: /home/ansible/hms
        clone: yes
        update: yes
        force: true
      become: true

      
    - name: install nodemon
      command: chdir=/home/ansible/hms npm install nodemon
      become: true
      

    - name: Go to the folder and execute command
      command: chdir=/home/ansible/hms npm install
      become: true

    - name: start server
      command: npm start
      args:
        chdir: /home/ansible/hms/
      async: 42
      poll: 0
      become: true
      ignore_errors: yes
