---
- hosts: any
  become: true
  tasks:

# tasks file for webapp

    - name: update
      command: sudo apt update
      become: true


    - name: install nodejs
      command: sudo apt install nodejs-legacy
      become: true
    
    - name: install npm
      command: sudo apt install npm -y

    - name: install git
      command: sudo apt install git
      become: true

    - name: Creates directory
      file:
        path: /home/adminuser/hms
        state: directory
      become: true

    - name: Clone a github repository
      git:
        repo: https://github.com/ManjunathNayak-23/Nodejsdemo.git
        dest: /home/adminuser/hms
        clone: yes
        update: yes
        force: true
      become: true

      
    - name: install nodemon
      command: chdir=/home/adminuser/hms sudo npm install -g nodemon
      become: true
      

    - name: Go to the folder and execute command
      command: chdir=/home/adminuser/hms sudo npm install
      become: true

    - name: start server
      command: chdir: /home/adminuser/hms/ sudo npm start
      become: true
        
      
