# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-new'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vmss scale --resource-group vmss-test --name vmss --new-capacity 1'
  displayName: 'Downscale VMSS to 1 instance'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-new'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      currentCapacity=$(az vmss show --resource-group vmss-test --name vmss --query 'sku.capacity' --output tsv)
          newCapacity=$((currentCapacity + 1))
          az vmss scale --resource-group vmss-test --name vmss --new-capacity $newCapacity
  displayName: 'Upscale VMSS to 1 instance(updated code)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-new'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
          instanceIdToDelete=$(az vmss list-instances --resource-group vmss-test --name vmss --query "[].instanceId"  --output tsv | sort -n | tail -n 1)
          az vmss delete-instances --resource-group vmss-test --name vmss --instance-ids $instanceIdToDelete --no-wait
  displayName: 'delete one old vm'

