# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: SSH@0
  inputs:
    sshEndpoint: 'bastin'
    runOptions: 'commands'
    commands: |
      cd ~
      echo $(pem) > vmsskey.pem
      chmod 400 vmsskey.pem
      ssh -i vmsskey.pem azureuser@20.119.195.215 cat /var/log/nginx/access.log > /home/azureuser/nginx.log
      cat /home/azureuser/nginx.log 
    readyTimeout: '20000'
# - task: SSH@0
#   inputs:
#     sshEndpoint: 'bastin'
#     runOptions: 'commands'
#     commands: |
#       ssh -i-azureuser@20.119.195.215 cat /var/log/nginx/access.log >> /home/azureuser/nginx.log
#     readyTimeout: '20000'
